// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYdYlFihFl3lISGvNfxVUXViAj8r_PqE',
    appId: '1:825598801807:web:8db1e48ef7f8b07f26bdfa',
    messagingSenderId: '825598801807',
    projectId: 'rimappmuaritania',
    authDomain: 'rimappmuaritania.firebaseapp.com',
    storageBucket: 'rimappmuaritania.firebasestorage.app',
    measurementId: 'G-CCJ242BV50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBR_m0-WOc5sg41DrQDyJtIxPPYLByeeQ',
    appId: '1:825598801807:android:d19c6fd9f269764c26bdfa',
    messagingSenderId: '825598801807',
    projectId: 'rimappmuaritania',
    storageBucket: 'rimappmuaritania.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0jNKx5yWF2kac4l1aGl3-zXniRrncho',
    appId: '1:825598801807:ios:fd5178487f7da32c26bdfa',
    messagingSenderId: '825598801807',
    projectId: 'rimappmuaritania',
    storageBucket: 'rimappmuaritania.firebasestorage.app',
    iosBundleId: 'com.example.wassalniDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0jNKx5yWF2kac4l1aGl3-zXniRrncho',
    appId: '1:825598801807:ios:fd5178487f7da32c26bdfa',
    messagingSenderId: '825598801807',
    projectId: 'rimappmuaritania',
    storageBucket: 'rimappmuaritania.firebasestorage.app',
    iosBundleId: 'com.example.wassalniDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwYdYlFihFl3lISGvNfxVUXViAj8r_PqE',
    appId: '1:825598801807:web:a07eac4075ff75f526bdfa',
    messagingSenderId: '825598801807',
    projectId: 'rimappmuaritania',
    authDomain: 'rimappmuaritania.firebaseapp.com',
    storageBucket: 'rimappmuaritania.firebasestorage.app',
    measurementId: 'G-TES03396F0',
  );

}