// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMnyjRS2PKPfmyHYjJFkx-VP5Qx60NGIs',
    appId: '1:434766781125:web:2c34be62a709143ca02eac',
    messagingSenderId: '434766781125',
    projectId: 'muari-course',
    authDomain: 'muari-course.firebaseapp.com',
    storageBucket: 'muari-course.firebasestorage.app',
    measurementId: 'G-M3J8C4T32D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3Kv5IhcCroUwCzOEbbEEfPY0WWhAEbc',
    appId: '1:434766781125:android:f967a295a0488901a02eac',
    messagingSenderId: '434766781125',
    projectId: 'muari-course',
    storageBucket: 'muari-course.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZ4iM1n8yRJCRv39sNxYMav-EBeAsWOk',
    appId: '1:434766781125:ios:345c761483830991a02eac',
    messagingSenderId: '434766781125',
    projectId: 'muari-course',
    storageBucket: 'muari-course.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZ4iM1n8yRJCRv39sNxYMav-EBeAsWOk',
    appId: '1:434766781125:ios:345c761483830991a02eac',
    messagingSenderId: '434766781125',
    projectId: 'muari-course',
    storageBucket: 'muari-course.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMnyjRS2PKPfmyHYjJFkx-VP5Qx60NGIs',
    appId: '1:434766781125:web:5fe99367d6afded0a02eac',
    messagingSenderId: '434766781125',
    projectId: 'muari-course',
    authDomain: 'muari-course.firebaseapp.com',
    storageBucket: 'muari-course.firebasestorage.app',
    measurementId: 'G-F6YMYQ2S5E',
  );

}